### ISSUE TITLE
[1.20.1] Crash when resurrecting a Vengeance Spirit with no Spawn Egg

### ISSUE THREAD

**Issue by FoxMcloud5655** [rubensworks/EvilCraft#1005]
#### Issue type:

- :bug: Bug

____

#### Short description:

When attempting to resurrect a Vengeance Spirit and create a Spawn Egg of it, if there is no associated Spawn Egg, the game crashes every time the chunk is loaded.

#### Steps to reproduce the problem:

1. For an example, let's grab the mod Iron's Spellbooks.  Grab a Spawn Egg for the Dead King Corpse.
2. Grab appropriate equipment for capturing Vengance Spirits (the ring and the focus along with a Box of Eternal Closure).
3. Spawn in the Dead King Corpse, wait for the animation, then kill the Dead King.
4. Capture the Vengeance Spirit.
5. Use the Spirit Reanimator with the captured spirit.

#### Expected behaviour:

To do nothing, auto-add it to a blacklist of some sort, or fail to create the Spawn Egg with an error message in chat.

____

#### Versions:

- This mod: 1.2.29
- Minecraft: 1.20.1
- Forge: 47.1.3
- Iron's Spellbooks: 1.2.1

#### Log file:

Relevent part of the crash:
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.ItemLike.m_5456_()" because "p_41604_" is null
	at net.minecraft.world.item.ItemStack.<init>(ItemStack.java:147) ~[server-1.20.1-20230612.114412-srg.jar%23577!/:?]
	at net.minecraft.world.item.ItemStack.<init>(ItemStack.java:143) ~[server-1.20.1-20230612.114412-srg.jar%23577!/:?]
	at net.minecraft.world.item.ItemStack.<init>(ItemStack.java:127) ~[server-1.20.1-20230612.114412-srg.jar%23577!/:?]
	at org.cyclops.evilcraft.blockentity.tickaction.spiritreanimator.ReanimateTickAction.getSpawnEgg(ReanimateTickAction.java:30) ~[EvilCraft-1.20.1-1.2.29.jar%23426!/:1.2.29]
	at org.cyclops.evilcraft.blockentity.tickaction.spiritreanimator.ReanimateTickAction.onTick(ReanimateTickAction.java:41) ~[EvilCraft-1.20.1-1.2.29.jar%23426!/:1.2.29]
	at org.cyclops.evilcraft.blockentity.tickaction.spiritreanimator.ReanimateTickAction.onTick(ReanimateTickAction.java:22) ~[EvilCraft-1.20.1-1.2.29.jar%23426!/:1.2.29]
	at org.cyclops.evilcraft.core.blockentity.tickaction.TickComponent.tick(TickComponent.java:142) ~[EvilCraft-1.20.1-1.2.29.jar%23426!/:1.2.29]
	at org.cyclops.evilcraft.core.blockentity.BlockEntityTickingTankInventory$TickerServer.update(BlockEntityTickingTankInventory.java:116) ~[EvilCraft-1.20.1-1.2.29.jar%23426!/:1.2.29]
	at org.cyclops.evilcraft.core.blockentity.BlockEntityWorking$TickerServer.update(BlockEntityWorking.java:387) ~[EvilCraft-1.20.1-1.2.29.jar%23426!/:1.2.29]
	at org.cyclops.evilcraft.core.blockentity.BlockEntityWorking$TickerServer.update(BlockEntityWorking.java:383) ~[EvilCraft-1.20.1-1.2.29.jar%23426!/:1.2.29]
	at org.cyclops.cyclopscore.blockentity.BlockEntityTickerDelayed.m_155252_(BlockEntityTickerDelayed.java:35) ~[CyclopsCore-1.20.1-1.18.10.jar%23413!/:1.18.10]
```

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by FoxMcloud5655** [comment]
Thanks!
