### ISSUE TITLE
Warn of c2me

### ISSUE THREAD

**Issue by coco875** [rubensworks/EvilCraft#1064]
#### Issue type:

- :bug: Bug 

____

#### Short description:

while playing with emi loot, emi don't load this kind of error appears
```log
This is usually NOT a bug in C2ME, but a bug in another mod or in vanilla code. 
Possible solutions: 
  - Find possible causes in the stack trace below and 
    - if caused by another mod, report this to the corresponding mod authors 
    - if no other mods are involved, report this to C2ME 

java.util.ConcurrentModificationException: ThreadLocalRandom accessed from a different thread (owner: Render thread, current: Thread-105)
	at TRANSFORMER/c2me_fixes_worldgen_threading_issues@0.3.0alpha.0.1501.21.1/com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.handleNotOwner(CheckedThreadLocalRandom.java:55) ~[c2me-fabric-mc1.21.1-0.3.0+alpha.0.150$c2me-fixes-worldgen-threading-issues-mc1.21.1-0.3.0+alpha.0.150_mapped_moj_1.21.1.jar%231872!/:?]
	at TRANSFORMER/c2me_fixes_worldgen_threading_issues@0.3.0alpha.0.1501.21.1/com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.isSafe(CheckedThreadLocalRandom.java:38) ~[c2me-fabric-mc1.21.1-0.3.0+alpha.0.150$c2me-fixes-worldgen-threading-issues-mc1.21.1-0.3.0+alpha.0.150_mapped_moj_1.21.1.jar%231872!/:?]
	at TRANSFORMER/c2me_fixes_worldgen_threading_issues@0.3.0alpha.0.1501.21.1/com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.next(CheckedThreadLocalRandom.java:86) ~[c2me-fabric-mc1.21.1-0.3.0+alpha.0.150$c2me-fixes-worldgen-threading-issues-mc1.21.1-0.3.0+alpha.0.150_mapped_moj_1.21.1.jar%231872!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.levelgen.BitRandomSource.nextInt(BitRandomSource.java:33) ~[client-1.21.1-20240808.144430-srg.jar%23529!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.Mth.nextInt(net/minecraft/util/Mth.java:160) ~[client-1.21.1-20240808.144430-srg.jar%23529!/:?]
	at TRANSFORMER/evilcraft@1.2.57/org.cyclops.evilcraft.entity.monster.EntityVengeanceSpirit.<init>(EntityVengeanceSpirit.java:140) ~[EvilCraft-1.21.1-neoforge-1.2.57.jar%23654!/:1.2.57]
	at TRANSFORMER/evilcraft@1.2.57/org.cyclops.evilcraft.entity.monster.EntityVengeanceSpirit.<init>(EntityVengeanceSpirit.java:126) ~[EvilCraft-1.21.1-neoforge-1.2.57.jar%23654!/:1.2.57]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.EntityType.create(net/minecraft/world/entity/EntityType.java:1097) ~[client-1.21.1-20240808.144430-srg.jar%23529!/:?]
	at TRANSFORMER/emi_loot@0.7.3+1.21+neoforge/fzzyhmstrs.emi_loot.emi.MobLootRecipe.<init>(MobLootRecipe.java:61) ~[emi_loot-0.7.3+1.21+neoforge.jar%23642!/:?]
	at TRANSFORMER/emi_loot@0.7.3+1.21+neoforge/fzzyhmstrs.emi_loot.emi.EmiClientPlugin.lambda$register$0(EmiClientPlugin.java:50) ~[emi_loot-0.7.3+1.21+neoforge.jar%23642!/:?]
	at java.base/java.lang.Iterable.forEach(Unknown Source) ~[?:?]
	at TRANSFORMER/emi_loot@0.7.3+1.21+neoforge/fzzyhmstrs.emi_loot.emi.EmiClientPlugin.register(EmiClientPlugin.java:41) ~[emi_loot-0.7.3+1.21+neoforge.jar%23642!/:?]
	at TRANSFORMER/emi@1.1.13+1.21.1+neoforge/dev.emi.emi.runtime.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:185) ~[emi-1.1.13+1.21.1+neoforge.jar%23640!/:?]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
```

#### Steps to reproduce the problem:

Normally with only connector, ffapi, c2me, evilcraft, emi, emi loot,  it will pop in log. (maybe there is also other issue with generation don't try)

#### Expected behaviour:

this kind of error should not appears

____

#### Versions:

- This mod: 1.2.57
- Minecraft: 1.21.1
- Mod loader version: 21.1.61

other mod version:
connector 2.0.0-beta.3+1.21.1
forgified-fabric-api-0.104.0+2.0.13+1.21.1
c2me-fabric-mc1.21.1-0.3.0+alpha.0.212
emi-1.1.13+1.21.1+neoforge
emi_loot-0.7.3+1.21+neoforge

#### Log file:

https://pastebin.com/kKYdmQmy

**Comment by rubensworks** [comment]
Thanks for reporting!
