### ISSUE TITLE
Blood Infusor crush

### ISSUE THREAD

**Issue by slammaja** [rubensworks/EvilCraft#239]
Hi,

I have forge 10.13.3.1388 installed and I crash everytime I try to put something into Blood Infusor in slot left from "progress" arrow. Im getting this:

Description: Unexpected error

java.lang.NullPointerException: Unexpected error
at net.minecraft.crash.CrashReportCategory.func_85069_a(CrashReportCategory.java:145)
at net.minecraft.crash.CrashReport.func_85057_a(CrashReport.java:390)
at net.minecraft.crash.CrashReport.func_85058_a(CrashReport.java:357)
at net.minecraft.client.Minecraft.func_71407_l(Unknown Source)
at net.minecraft.client.Minecraft.func_71411_J(Unknown Source)
at net.minecraft.client.Minecraft.func_99999_d(Unknown Source)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Im running the latest version, tried every version before that (for MC 1.7.10), but still the same problem. Other machines seem to work fine. Any idea what may cause it?

Thanks.

**Comment by rubensworks** [comment]
This is the same problem as in #235, please update your Forge to a later version (or to an earlier version), your Forge version is bugged.

**Comment by slammaja** [comment]
Oh, thanks, sorry for new post!

**Comment by rubensworks** [comment]
No problem, if the Forge update works for you, you can close this issue.

**Comment by slammaja** [comment]
It worked, btw love this mod :)

**Comment by rubensworks** [comment]
Cool, glad you like it.
