### ISSUE TITLE
Server crash with blood extractor

### ISSUE THREAD

**Issue by LemADEC** [rubensworks/EvilCraft#249]
We had a server crash when a flail projectile from Balkon's weapon mod was used to kill a Zombie.
Notable mod versions:
- weaponmod-1.14.3,
- EvilCraft-1.7.10-0.8.7,
- Forge Mod Loader version 7.99.4.1481 for Minecraft 1.7.10

```
java.lang.IllegalArgumentException: bound must be positive
        at java.util.Random.nextInt(Random.java:388)
        at evilcraft.item.BloodExtractor.fillForAllBloodExtractors(BloodExtractor.java:144)
        at evilcraft.event.LivingDeathEventHook.bloodObtainEvent(LivingDeathEventHook.java:69)
        at evilcraft.event.LivingDeathEventHook.onLivingDeath(LivingDeathEventHook.java:49)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_155_LivingDeathEventHook_onLivingDeath_LivingDeathEvent.invoke(.dynamic)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
        at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:313)
        at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1016)
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:980)
        at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:71)
        at net.minecraft.entity.monster.EntityZombie.func_70097_a(EntityZombie.java:249)
        at ckathode.weaponmod.entity.projectile.EntityFlail.onEntityHit(EntityFlail.java:176)
        at ckathode.weaponmod.entity.projectile.EntityProjectile.func_70030_z(EntityProjectile.java:242)
        at ckathode.weaponmod.entity.projectile.EntityProjectile.func_70071_h_(EntityProjectile.java:140)
        at ckathode.weaponmod.entity.projectile.EntityFlail.func_70071_h_(EntityFlail.java:62)
        at net.minecraft.world.World.func_72866_a(World.java:2655)
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837)
        at net.minecraft.world.World.func_72870_g(World.java:2607)
        at net.minecraft.world.World.func_72939_s(World.java:2423)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
        at java.lang.Thread.run(Thread.java:745)
```

Related configuration values:

```
    # The maximum multiplier for amount of mB to receive per mob HP. IMPORTANT: must be larger than maximumMobMultiplier!
    D:bloodExtractor.maximumMobMultiplier=40.0

    # The minimum multiplier for amount of mB to receive per mob HP.
    D:bloodExtractor.minimumMobMultiplier=5.0
```

Full crash log is available here: http://pastebin.com/qLW8EV3p
Full mod configuration file is available here: http://pastebin.com/WcbeMQiH

**Comment by rubensworks** [comment]
Thanks for reporting, the issue is known.
I should really get around to fixing it.
