### ISSUE TITLE
blood infuser crash

### ISSUE THREAD

**Issue by kalela7** [rubensworks/EvilCraft#318]
Crash while trying to put any item http://hastebin.com/fupelotuge.hs

**Comment by rubensworks** [comment]
Looks like the same issue as #235, which should've been fixed by Forge a long time ago.
Could you try re-installing Forge or downgrading to a recommended version of Forge?

**Comment by kalela7** [comment]
Thanks Now I understand how making assembly and realized that now I have to look for old versions of all mods for this version of The Forge : D

**Comment by rubensworks** [comment]
I highly doubt that you will have to use other mod versions for working with the latest recommended version of Forge, mods will typically depend on a recommended version instead of the very latest version.

**Comment by kalela7** [comment]
Okay thanks for the quick response, Then the very disassemble.

**Comment by rubensworks** [comment]
@kalela7 Are you still experiencing this issue? If not, you can close this issue.

**Comment by Blue64** [comment]
@kalela7

```
[09:48:24] [Client thread/ERROR] [FML]: The mcmod.info file in TaintedMagic-1.1.6.4.jar cannot be parsed as valid JSON. It will be ignored
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 7 column 5
    at com.google.gson.internal.Streams.parse(Streams.java:56) ~[Streams.class:?]
    at com.google.gson.JsonParser.parse(JsonParser.java:84) ~[JsonParser.class:?]
    at com.google.gson.JsonParser.parse(JsonParser.java:59) ~[JsonParser.class:?]
    at cpw.mods.fml.common.MetadataCollection.from(MetadataCollection.java:55) [MetadataCollection.class:?]
    at cpw.mods.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:53) [JarDiscoverer.class:?]
    at cpw.mods.fml.common.discovery.ContainerType.findMods(ContainerType.java:42) [ContainerType.class:?]
    at cpw.mods.fml.common.discovery.ModCandidate.explore(ModCandidate.java:71) [ModCandidate.class:?]
    at cpw.mods.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:131) [ModDiscoverer.class:?]
    at cpw.mods.fml.common.Loader.identifyMods(Loader.java:364) [Loader.class:?]
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:489) [Loader.class:?]
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208) [FMLClientHandler.class:?]
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 7 column 5
    at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505) ~[JsonReader.class:?]
    at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:480) ~[JsonReader.class:?]
    at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:403) ~[JsonReader.class:?]
    at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:666) ~[TypeAdapters$25.class:?]
    at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:659) ~[TypeAdapters$25.class:?]
    at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:642) ~[TypeAdapters$25.class:?]
    at com.google.gson.internal.Streams.parse(Streams.java:44) ~[Streams.class:?]
    ... 19 more
```

Check the line above it. I encountered a similar issue recently. Make sure you tell TaintedMagic about their problem, and verify you are using the correct version for your MineCraft `(1.7.0~1.7.10)`
