### ISSUE TITLE
Boxing Vengeance Spirits crashes the server

### ISSUE THREAD

**Issue by Yoghurt4C** [rubensworks/EvilCraft#345]
Description: Saving entity NBT

java.lang.NullPointerException: Saving entity NBT
    at net.minecraft.entity.Entity.func_70109_d(Entity.java:1345)
    at org.cyclops.evilcraft.tileentity.TileBoxOfEternalClosure.setSpiritInstance(TileBoxOfEternalClosure.java:224)
    at org.cyclops.evilcraft.tileentity.TileBoxOfEternalClosure.pullEntity(TileBoxOfEternalClosure.java:150)
    at org.cyclops.evilcraft.tileentity.TileBoxOfEternalClosure.updateTileEntity(TileBoxOfEternalClosure.java:103)
    at org.cyclops.cyclopscore.tileentity.CyclopsTileEntity.updateTicking(CyclopsTileEntity.java:86)
    at org.cyclops.cyclopscore.tileentity.CyclopsTileEntity.access$000(CyclopsTileEntity.java:31)
    at org.cyclops.cyclopscore.tileentity.CyclopsTileEntity$TickingTileComponent.func_73660_a(CyclopsTileEntity.java:283)
    at org.cyclops.evilcraft.tileentity.TileBoxOfEternalClosure.func_73660_a(TileBoxOfEternalClosure.java:54)
    at net.minecraft.world.World.func_72939_s(World.java:1718)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Unknown Source)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.entity.Entity.func_70109_d(Entity.java:1345)

-- Entity being saved --
Details:
    Entity Type: evilcraft.vengeanceSpirit (org.cyclops.evilcraft.entity.monster.VengeanceSpirit)
    Entity ID: 34536
    Entity Name: Vengeance Spirit
    Entity's Exact location: 390.07, 67.26, 962.62
    Entity's Block location: 390.00,67.00,962.00 - World: (390,67,962), Chunk: (at 6,4,2 in 24,60; contains blocks 384,0,960 to 399,255,975), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
    Entity's Momentum: 0.00, 0.00, 0.00
    Entity's Rider: ~~ERROR~~ NullPointerException: null
    Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
    at net.minecraft.entity.Entity.func_70109_d(Entity.java:1345)
    at org.cyclops.evilcraft.tileentity.TileBoxOfEternalClosure.setSpiritInstance(TileBoxOfEternalClosure.java:224)
    at org.cyclops.evilcraft.tileentity.TileBoxOfEternalClosure.pullEntity(TileBoxOfEternalClosure.java:150)
    at org.cyclops.evilcraft.tileentity.TileBoxOfEternalClosure.updateTileEntity(TileBoxOfEternalClosure.java:103)
    at org.cyclops.cyclopscore.tileentity.CyclopsTileEntity.updateTicking(CyclopsTileEntity.java:86)
    at org.cyclops.cyclopscore.tileentity.CyclopsTileEntity.access$000(CyclopsTileEntity.java:31)
    at org.cyclops.cyclopscore.tileentity.CyclopsTileEntity$TickingTileComponent.func_73660_a(CyclopsTileEntity.java:283)
    at org.cyclops.evilcraft.tileentity.TileBoxOfEternalClosure.func_73660_a(TileBoxOfEternalClosure.java:54)

-- Block entity being ticked --
Details:
    Name: boxOfEternalClosure // org.cyclops.evilcraft.tileentity.TileBoxOfEternalClosure
    Block type: ID #988 (tile.blocks.evilcraft.boxOfEternalClosure // org.cyclops.evilcraft.block.BoxOfEternalClosure)
    Block data value: 1 / 0x1 / 0b0001
    Block location: World: (391,67,961), Chunk: (at 7,4,1 in 24,60; contains blocks 384,0,960 to 399,255,975), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
    Actual block type: ID #988 (tile.blocks.evilcraft.boxOfEternalClosure // org.cyclops.evilcraft.block.BoxOfEternalClosure)
    Actual block data value: 1 / 0x1 / 0b0001
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1718)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)

-- Affected level --
Details:
    Level name: world
    All players: 1 total; [EntityPlayerMP['Yoghurt4C'/34400, l='world', x=392.06, y=67.00, z=957.41]]
    Chunk stats: ServerChunkCache: 824 Drop: 0
    Level seed: -6881065225674408322
    Level generator: ID 06 - RTG, ver 0. Features enabled: true
    Level generator options:
    Level spawn location: 0.00,64.00,0.00 - World: (0,64,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 17945101 game time, 18157106 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 1407 (now: true), thunder time: 69705 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_66, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation

**Comment by rubensworks** [comment]
Thanks for reporting this.

Which EvilCraft version were you using?
What did you do that resulted in the crash?

**Comment by Yoghurt4C** [comment]
latest (which is 0.9.3)
as it's said in the title, I tried to capture a vengeance spirit in an empty box.

**Comment by rubensworks** [comment]
Yes, ok, that was clear.
But which spirit were you trying to capture? From where did that spirit originate? How did you obtain the box?

**Comment by Yoghurt4C** [comment]
the crash actually happened twice: the first time it was a cow, and the second time it was a white sheep. two different boxes were used.
the spirits originated from living mobs that got killed.
the first box came from a dungeon chest, and I've successfully used it 3 times before the crashes started happening for whatever reason. the second box was manually crafted and used "fresh".
the crashlogs are pretty much the same, except for mobs and coordinates.

**Comment by rubensworks** [comment]
It's strange that it worked a few times before crashing... I'll look into it, thanks for reporting this! :)

**Comment by rubensworks** [comment]
I was not able to reproduce your crash, but I've added an extra check which should solve this eitherway.
@Yoghurt4C If you want, you can test the latest [dev build](https://bintray.com/cyclopsmc/dev/EvilCraft/view). In that case, let me know if you still encounter the crash.
