### ISSUE TITLE
Server Crash - ImplicitFluidConverter

### ISSUE THREAD

**Issue by Sir-Will** [rubensworks/EvilCraft#350]
MC: 1.7.10 - Mod: 0.9.4

```
java.lang.NullPointerException: Exception in server tick loop
    at evilcraft.core.fluid.ImplicitFluidConverter.getRatio(ImplicitFluidConverter.java:106)
    at evilcraft.core.fluid.ImplicitFluidConversionTank.fill(ImplicitFluidConversionTank.java:32)
    at evilcraft.core.tileentity.TankInventoryTileEntity.fill(TankInventoryTileEntity.java:126)
    at crazypants.enderio.conduit.liquid.LiquidConduitNetwork.flowFrom(LiquidConduitNetwork.java:234)
    at crazypants.enderio.conduit.liquid.LiquidConduitNetwork.doFlow(LiquidConduitNetwork.java:105)
    at crazypants.enderio.conduit.liquid.LiquidConduitNetwork.doNetworkTick(LiquidConduitNetwork.java:75)
    at crazypants.enderio.conduit.ConduitNetworkTickHandler.tickEnd(ConduitNetworkTickHandler.java:63)
    at crazypants.enderio.conduit.ConduitNetworkTickHandler.onServerTick(ConduitNetworkTickHandler.java:47)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_345_ConduitNetworkTickHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:251)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:862)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by rubensworks** [comment]
What is your setup that caused this crash? Does this always happen? Or just this once?

**Comment by Sir-Will** [comment]
I don't know. It's from a other player and I tried to remove the tanks in the area with mcedit but it still crashes on loading the chunks there.

**Comment by rubensworks** [comment]
Could you ask that player those questions? Because I don't see how this crash could occur without some funky cross-mod interaction.

**Comment by Sir-Will** [comment]
He placed a blood chest here where the bedrock is:
![](http://i.imgur.com/i3iyKg8.png)

After removing it the issue was gone.

**Comment by rubensworks** [comment]
I'll look into it, thanks for reporting.

**Comment by M4sterOx** [comment]
Hey sorry for the late response, but i have a crash post now and later I'm going to post the complete set-up.

**Comment by M4sterOx** [comment]
Forgot to add the paste bin sorry http://pastebin.com/fi0uZBBN and the link to the video https://www.youtube.com/watch?v=7aXnm6oRNKg

**Comment by rubensworks** [comment]
@M4sterOx Thanks for the video! This makes it very easy for me to reproduce this :+1: 
I'll try to look into it next somewhere week.
