### ISSUE TITLE
1.9 crash when using spirit furnace

### ISSUE THREAD

**Issue by 0Heatseeker0** [rubensworks/EvilCraft#369]
---- Minecraft Crash Report ----
// Why did you do that?

Time: 3/20/16 10:16 AM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
    at net.minecraftforge.client.model.ModelLoader$2.compare(ModelLoader.java:183)
    at net.minecraftforge.client.model.ModelLoader$2.compare(ModelLoader.java:180)
    at java.util.TimSort.binarySort(Unknown Source)
    at java.util.TimSort.sort(Unknown Source)
    at java.util.Arrays.sort(Unknown Source)
    at java.util.ArrayList.sort(Unknown Source)
    at java.util.Collections.sort(Unknown Source)
    at net.minecraftforge.client.model.ModelLoader.func_188640_b(ModelLoader.java:179)
    at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:118)
    at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:130)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:111)
    at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:756)
    at net.minecraft.client.gui.GuiScreenResourcePacks.func_146284_a(SourceFile:133)
    at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:451)
    at net.minecraft.client.gui.GuiScreenResourcePacks.func_73864_a(SourceFile:141)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:539)
    at net.minecraft.client.gui.GuiScreenResourcePacks.func_146274_d(SourceFile:77)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:508)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1694)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraftforge.client.model.ModelLoader$2.compare(ModelLoader.java:183)
    at net.minecraftforge.client.model.ModelLoader$2.compare(ModelLoader.java:180)
    at java.util.TimSort.binarySort(Unknown Source)
    at java.util.TimSort.sort(Unknown Source)
    at java.util.Arrays.sort(Unknown Source)
    at java.util.ArrayList.sort(Unknown Source)
    at java.util.Collections.sort(Unknown Source)
    at net.minecraftforge.client.model.ModelLoader.func_188640_b(ModelLoader.java:179)
    at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:118)
    at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:130)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:111)
    at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:756)
    at net.minecraft.client.gui.GuiScreenResourcePacks.func_146284_a(SourceFile:133)
    at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:451)
    at net.minecraft.client.gui.GuiScreenResourcePacks.func_73864_a(SourceFile:141)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:539)
    at net.minecraft.client.gui.GuiScreenResourcePacks.func_146274_d(SourceFile:77)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:508)

-- Affected screen --
Details:
    Screen name: net.minecraft.client.gui.GuiScreenResourcePacks

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['0HeatSeeker0'/28, l='MpServer', x=-1268.50, y=92.00, z=1373.50]]
    Chunk stats: MultiplayerChunkCache: 625, 625
    Level seed: 0
    Level generator: ID 04 - customized, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-1134,70,2185), Chunk: (at 2,4,9 in -71,136; contains blocks -1136,0,2176 to -1121,255,2191), Region: (-3,4; contains chunks -96,128 to -65,159, blocks -1536,0,2048 to -1025,255,2559)
    Level time: 809657 game time, 6056 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 77 total; [EntityItem['item.item.dyePowder.black'/6144, l='MpServer', x=-1267.88, y=47.00, z=1367.35], EntityItem['item.item.dyePowder.black'/129, l='MpServer', x=-1264.13, y=46.00, z=1366.47], EntityZombie['Zombie'/6146, l='MpServer', x=-1317.50, y=32.00, z=1395.50], EntityBat['Bat'/5381, l='MpServer', x=-1224.60, y=24.22, z=1387.80], EntityBat['Bat'/5383, l='MpServer', x=-1228.25, y=23.06, z=1398.25], EntityItem['item.item.rottenFlesh'/136, l='MpServer', x=-1248.36, y=91.00, z=1346.63], EntitySkeleton['Skeleton'/6154, l='MpServer', x=-1297.50, y=37.00, z=1397.50], EntitySkeleton['Skeleton'/4367, l='MpServer', x=-1281.72, y=81.00, z=1331.48], EntityZombie['Zombie'/5140, l='MpServer', x=-1327.50, y=32.00, z=1297.50], EntityBat['Bat'/5657, l='MpServer', x=-1336.25, y=46.04, z=1308.50], EntityCreeper['Creeper'/2458, l='MpServer', x=-1343.50, y=15.00, z=1427.50], EntityBat['Bat'/5659, l='MpServer', x=-1205.25, y=58.10, z=1347.75], EntityBat['Bat'/5660, l='MpServer', x=-1307.47, y=18.70, z=1309.25], EntityPlayerSP['0HeatSeeker0'/28, l='MpServer', x=-1268.50, y=92.00, z=1373.50], EntityBat['Bat'/6047, l='MpServer', x=-1323.68, y=32.39, z=1408.35], EntityZombie['Zombie'/1440, l='MpServer', x=-1311.50, y=33.00, z=1300.50], EntityCreeper['Creeper'/4643, l='MpServer', x=-1315.50, y=19.00, z=1432.50], EntityCreeper['Creeper'/4771, l='MpServer', x=-1314.50, y=24.00, z=1313.50], EntityCreeper['Creeper'/5923, l='MpServer', x=-1203.50, y=28.00, z=1369.50], EntityCreeper['Creeper'/4264, l='MpServer', x=-1308.50, y=37.00, z=1373.50], EntityZombie['Zombie'/6061, l='MpServer', x=-1331.50, y=34.00, z=1443.50], EntitySkeleton['Skeleton'/5296, l='MpServer', x=-1327.50, y=34.00, z=1310.50], EntityZombie['Zombie'/5298, l='MpServer', x=-1285.50, y=17.00, z=1448.50], EntitySkeleton['Skeleton'/5427, l='MpServer', x=-1304.50, y=51.00, z=1298.50], EntityBat['Bat'/4279, l='MpServer', x=-1321.63, y=61.13, z=1384.71], EntityCreeper['Creeper'/6071, l='MpServer', x=-1318.22, y=32.00, z=1405.44], EntitySkeleton['Skeleton'/5432, l='MpServer', x=-1344.50, y=15.00, z=1419.50], EntitySkeleton['Skeleton'/5688, l='MpServer', x=-1304.50, y=68.00, z=1362.50], EntitySeat['entity.mfs.Seat.name'/6077, l='MpServer', x=-1270.00, y=92.20, z=1373.00], EntitySpider['Spider'/6208, l='MpServer', x=-1224.50, y=22.00, z=1396.50], EntitySkeleton['Skeleton'/65, l='MpServer', x=-1344.50, y=38.00, z=1447.50], EntityCreeper['Creeper'/5187, l='MpServer', x=-1299.50, y=41.00, z=1394.50], EntityBat['Bat'/5956, l='MpServer', x=-1192.25, y=39.02, z=1322.25], EntityCreeper['Creeper'/2245, l='MpServer', x=-1317.50, y=66.00, z=1365.50], EntityCreeper['Creeper'/6213, l='MpServer', x=-1311.50, y=37.00, z=1373.50], EntityItem['item.item.spiderEye'/1990, l='MpServer', x=-1328.87, y=91.00, z=1392.84], EntityZombie['Zombie'/4041, l='MpServer', x=-1281.50, y=55.00, z=1369.50], EntityBat['Bat'/3018, l='MpServer', x=-1334.90, y=39.19, z=1452.82], EntityZombie['Zombie'/5710, l='MpServer', x=-1330.50, y=14.00, z=1441.50], EntityZombie['Zombie'/5714, l='MpServer', x=-1199.50, y=33.00, z=1329.50], EntityZombie['Zombie'/5974, l='MpServer', x=-1212.50, y=12.00, z=1392.50], EntityZombie['Zombie'/89, l='MpServer', x=-1323.20, y=67.00, z=1365.49], EntityBat['Bat'/5595, l='MpServer', x=-1270.75, y=37.81, z=1390.75], EntitySkeleton['Skeleton'/4060, l='MpServer', x=-1306.50, y=32.00, z=1308.50], EntityZombie['Zombie'/4444, l='MpServer', x=-1344.50, y=45.00, z=1296.50], EntityBat['Bat'/5852, l='MpServer', x=-1301.80, y=19.01, z=1333.25], EntityMinecartChest['container.minecart'/93, l='MpServer', x=-1318.50, y=32.06, z=1404.11], EntityZombie['Zombie'/2654, l='MpServer', x=-1343.50, y=15.00, z=1420.50], EntityBat['Bat'/5854, l='MpServer', x=-1244.25, y=18.10, z=1372.54], EntityMC172['entity.mfs.MC172.name'/5733, l='MpServer', x=-1270.00, y=92.30, z=1373.00], EntityCore['entity.mfs.Core.name'/5734, l='MpServer', x=-1270.37, y=92.00, z=1372.07], EntityCore['entity.mfs.Core.name'/5735, l='MpServer', x=-1268.44, y=92.02, z=1376.95], EntityCreeper['Creeper'/3560, l='MpServer', x=-1309.50, y=40.00, z=1297.50], EntityCreeper['Creeper'/5992, l='MpServer', x=-1276.50, y=74.00, z=1450.50], EntityCreeper['Creeper'/3561, l='MpServer', x=-1301.50, y=17.00, z=1331.50], EntitySkeleton['Skeleton'/106, l='MpServer', x=-1307.50, y=67.00, z=1370.50], EntityZombie['Zombie'/5996, l='MpServer', x=-1189.50, y=32.00, z=1312.50], EntityMinecartChest['container.minecart'/109, l='MpServer', x=-1302.50, y=33.06, z=1394.50], EntityZombie['Zombie'/5869, l='MpServer', x=-1303.50, y=19.00, z=1430.50], EntityCreeper['Creeper'/5359, l='MpServer', x=-1324.50, y=22.00, z=1413.50], EntityArmorStand['Armor Stand'/112, l='MpServer', x=-1298.50, y=92.00, z=1413.50], EntityMinecartChest['container.minecart'/113, l='MpServer', x=-1299.50, y=38.06, z=1429.50], EntityEnderman['Enderman'/4978, l='MpServer', x=-1316.50, y=39.00, z=1313.50], EntityCreeper['Creeper'/5362, l='MpServer', x=-1200.50, y=33.00, z=1346.50], EntityZombie['Zombie'/5490, l='MpServer', x=-1326.50, y=23.00, z=1411.50], EntityCreeper['Creeper'/3958, l='MpServer', x=-1309.50, y=17.00, z=1376.50], EntityItem['item.item.arrow'/118, l='MpServer', x=-1295.62, y=92.00, z=1356.12], EntityItem['item.item.bone'/119, l='MpServer', x=-1294.86, y=92.00, z=1357.14], EntityEnderman['Enderman'/121, l='MpServer', x=-1283.62, y=56.00, z=1371.51], EntityBat['Bat'/5369, l='MpServer', x=-1315.35, y=16.00, z=1327.80], EntitySpider['Spider'/4091, l='MpServer', x=-1326.50, y=23.00, z=1453.50], EntityBat['Bat'/6267, l='MpServer', x=-1336.23, y=31.12, z=1345.23], EntitySkeleton['Skeleton'/5244, l='MpServer', x=-1298.50, y=71.00, z=1452.50], EntityCreeper['Creeper'/6140, l='MpServer', x=-1201.50, y=32.00, z=1322.50], EntityHorse['Skeleton Horse'/125, l='MpServer', x=-1296.03, y=89.00, z=1383.30], EntityZombie['Zombie'/4733, l='MpServer', x=-1274.50, y=37.00, z=1394.50], EntityCreeper['Creeper'/6141, l='MpServer', x=-1317.50, y=34.00, z=1295.50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:409)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2647)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:387)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
    Minecraft Version: 1.9
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_71, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 348822240 bytes (332 MB) / 978321408 bytes (933 MB) up to 978321408 bytes (933 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP 9.23 Powered by Forge 12.16.0.1776 9 mods loaded, 9 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.9-12.16.0.1776-1.9-universal.jar) 
    UCHIJAAAA   Forge{12.16.0.1776} [Minecraft Forge](forge-1.9-12.16.0.1776-1.9-universal.jar) 
) 
    Loaded coremods (and transformers): 
    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '2.1.8870' Renderer: 'ATI Radeon HD 4200'
    Launched Version: MultiMC5
    LWJGL: 2.9.1
    OpenGL: ATI Radeon HD 4200 GL version 2.1.8870, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: No
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: DragonflyWings (incompatible)
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 4x AMD Athlon(tm) II X4 630 Processor
```

**Comment by rubensworks** [comment]
What did you do exactly to cause this crash?
Please use something like pastebin to post crash reports.

**Comment by rubensworks** [comment]
No details on how this crash occurred are given, so I'll close this issue.
