### ISSUE TITLE
BlockLiquid.LEVEL in EternalWaterBlock?

### ISSUE THREAD

**Issue by josephcsible** [rubensworks/EvilCraft#633]
https://github.com/CyclopsMC/EvilCraft/blob/e7daae344585e6d5f4183e5dbd7afc596ec9e183/src/main/java/org/cyclops/evilcraft/block/EternalWaterBlock.java#L33-L35

What's this for? EternalWaterBlock isn't a BlockLiquid AFAIK, so where would it ever get or use this?

**Comment by rubensworks** [comment]
This used to be required to not make the whole thing crash when using `Material.WATER`. This might have changed by now, feel free to try removing it.

**Comment by josephcsible** [comment]
Sigh, still crashes:
```
java.lang.IllegalArgumentException: Cannot get property PropertyInteger{name=level, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} as it does not exist in BlockStateContainer{block=evilcraft:eternal_water_block, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.getValue(BlockStateContainer.java:204) ~[BlockStateContainer$StateImplementation.class:?]
	at net.minecraft.block.BlockLiquid.getDepth(BlockLiquid.java:76) ~[BlockLiquid.class:?]
	at net.minecraft.block.BlockDynamicLiquid.checkAdjacentBlock(BlockDynamicLiquid.java:275) ~[BlockDynamicLiquid.class:?]
	at net.minecraft.block.BlockDynamicLiquid.updateTick(BlockDynamicLiquid.java:46) ~[BlockDynamicLiquid.class:?]
```

**Comment by josephcsible** [comment]
If MinecraftForge/MinecraftForge#4619 merges, we should look at this again.
