### ISSUE TITLE
Werevolf loot table is invalid on 1.10

### ISSUE THREAD

**Issue by LemADEC** [rubensworks/EvilCraft#659]
#### Issue type:
_Only keep the issue types that are applicable._
- :bug: Bug
____
#### Short description:
Exception in console when Werevolf villager dies.

#### Expected behaviour:
No exception/console spam

#### Actual behaviour:
Exception in console

#### Steps to reproduce the problem:

1. boot the game
2. spawn a werevolf
3. kill it

____
#### Versions:

- This mod: 1.10.2-0.10.29
- CyclopsCore: 1.9.4-0.10.10
- Minecraft: 1.10.2
- Forge: 12.18.3.2511

#### Log file:

```
[20:39:43] [Server thread/ERROR]: Couldn't load loot table evilcraft:entities/werewolf from jar:file:/home/imperium/mods/EvilCraft-1.10.2-0.10.29.jar!/assets/evilcraft/loot_tables/entities/werewolf.json
com.google.gson.JsonParseException: Loot Table "evilcraft:entities/werewolf" Missing `name` entry for pool #0
>       at net.minecraftforge.common.ForgeHooks.readPoolName(ForgeHooks.java:1139) ~[ForgeHooks.class:?]
>       at net.minecraft.world.storage.loot.LootPool$Serializer.deserialize(LootPool.java:143) ~[ban$a.class:?]
>       at net.minecraft.world.storage.loot.LootPool$Serializer.deserialize(LootPool.java:138) ~[ban$a.class:?]
>       at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58) ~[TreeTypeAdapter.class:?]
>       at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[TypeAdapterRuntimeTypeWrapper.class:?]
>       at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[ArrayTypeAdapter.class:?]
>       at com.google.gson.Gson.fromJson(Gson.java:803) ~[Gson.class:?]
>       at com.google.gson.Gson.fromJson(Gson.java:868) ~[Gson.class:?]
>       at com.google.gson.Gson$1.deserialize(Gson.java:126) ~[Gson$1.class:?]
>       at net.minecraft.util.JsonUtils.func_188179_a(SourceFile:449) ~[og.class:?]
>       at net.minecraft.util.JsonUtils.func_188177_a(SourceFile:465) ~[og.class:?]
>       at net.minecraft.world.storage.loot.LootTable$Serializer.deserialize(LootTable.java:206) ~[bap$a.class:?]
>       at net.minecraft.world.storage.loot.LootTable$Serializer.deserialize(LootTable.java:201) ~[bap$a.class:?]
>       at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58) ~[TreeTypeAdapter.class:?]
>       at com.google.gson.Gson.fromJson(Gson.java:803) ~[Gson.class:?]
>       at com.google.gson.Gson.fromJson(Gson.java:768) ~[Gson.class:?]
>       at com.google.gson.Gson.fromJson(Gson.java:717) ~[Gson.class:?]
>       at com.google.gson.Gson.fromJson(Gson.java:689) ~[Gson.class:?]
>       at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:1063) ~[ForgeHooks.class:?]
>       at net.minecraft.world.storage.loot.LootTableManager$Loader.func_186518_c(LootTableManager.java:148) [bas$a.class:?]
>       at net.minecraft.world.storage.loot.LootTableManager$Loader.load(LootTableManager.java:71) [bas$a.class:?]
>       at net.minecraft.world.storage.loot.LootTableManager$Loader.load(LootTableManager.java:52) [bas$a.class:?]
>       at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524) [minecraft_server.1.10.2.jar:?]
>       at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317) [minecraft_server.1.10.2.jar:?]
>       at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280) [minecraft_server.1.10.2.jar:?]
>       at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195) [minecraft_server.1.10.2.jar:?]
>       at com.google.common.cache.LocalCache.get(LocalCache.java:3934) [minecraft_server.1.10.2.jar:?]
>       at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938) [minecraft_server.1.10.2.jar:?]
>       at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821) [minecraft_server.1.10.2.jar:?]
>       at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827) [minecraft_server.1.10.2.jar:?]
>       at net.minecraft.world.storage.loot.LootTableManager.func_186521_a(LootTableManager.java:39) [bas.class:?]
``

**Comment by rubensworks** [comment]
Sorry, 1.10 is not maintained anymore.

**Comment by LemADEC** [comment]
Issue is still valid on 1.12.2-0.10.59:
```
[17:05:20] [Server thread/ERROR]: Couldn't load loot table evilcraft:entities/werewolf from jar:file:/home/wwm/_rho/./mods/EvilCraft-1.12.2-0.10.59.jar!/assets/evilcraft/loot_tables/entities/werewolf.json
com.google.gson.JsonParseException: Loot Table "evilcraft:entities/werewolf" Missing `name` entry for pool #0
>       at net.minecraftforge.common.ForgeHooks.readPoolName(ForgeHooks.java:1240) ~[ForgeHooks.class:?]
>       at net.minecraft.world.storage.loot.LootPool$Serializer.deserialize(LootPool.java:143) ~[bfq$a.class:?]
>       at net.minecraft.world.storage.loot.LootPool$Serializer.deserialize(LootPool.java:138) ~[bfq$a.class:?]
>       at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
>       at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[TypeAdapterRuntimeTypeWrapper.class:?]
>       at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[ArrayTypeAdapter.class:?]
>       at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
>       at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
>       at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[TreeTypeAdapter$GsonContextImpl.class:?]
>       at net.minecraft.util.JsonUtils.func_188179_a(SourceFile:439) ~[rc.class:?]
>       at net.minecraft.util.JsonUtils.func_188177_a(SourceFile:455) ~[rc.class:?]
>       at net.minecraft.world.storage.loot.LootTable$Serializer.deserialize(LootTable.java:204) ~[bfs$a.class:?]
>       at net.minecraft.world.storage.loot.LootTable$Serializer.deserialize(LootTable.java:199) ~[bfs$a.class:?]
>       at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
>       at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
>       at com.google.gson.Gson.fromJson(Gson.java:852) ~[Gson.class:?]
>       at com.google.gson.Gson.fromJson(Gson.java:801) ~[Gson.class:?]
>       at com.google.gson.Gson.fromJson(Gson.java:773) ~[Gson.class:?]
>       at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:1164) ~[ForgeHooks.class:?]
>       at net.minecraft.world.storage.loot.LootTableManager$Loader.func_186518_c(LootTableManager.java:156) [bfv$a.class:?]
>       at net.minecraft.world.storage.loot.LootTableManager$Loader.load(LootTableManager.java:72) [bfv$a.class:?]
>       at net.minecraft.world.storage.loot.LootTableManager$Loader.load(LootTableManager.java:53) [bfv$a.class:?]
>       at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) [minecraft_server.1.12.2.jar:?]
>       at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) [minecraft_server.1.12.2.jar:?]
>       at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) [minecraft_server.1.12.2.jar:?]
>       at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) [minecraft_server.1.12.2.jar:?]
>       at com.google.common.cache.LocalCache.get(LocalCache.java:4154) [minecraft_server.1.12.2.jar:?]
>       at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) [minecraft_server.1.12.2.jar:?]
>       at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) [minecraft_server.1.12.2.jar:?]
>       at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) [minecraft_server.1.12.2.jar:?]
>       at net.minecraft.world.storage.loot.LootTableManager.func_186521_a(LootTableManager.java:40) [bfv.class:?]
>       at net.minecraft.entity.EntityLiving.func_184610_a(EntityLiving.java:532) [vq.class:?]
>       at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1188) [vp.class:?]
>       at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1014) [vp.class:?]
>       at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:70) [ade.class:?]
>       at net.minecraft.entity.EntityLivingBase.func_180430_e(EntityLivingBase.java:1316) [vp.class:?]
>       at net.minecraft.block.Block.func_180658_a(Block.java:821) [aow.class:?]
>       at net.minecraft.entity.Entity.func_184231_a(Entity.java:1130) [vg.class:?]
>       at net.minecraft.entity.EntityLivingBase.func_184231_a(EntityLivingBase.java:213) [vp.class:?]
>       at net.minecraft.entity.Entity.func_70091_d(Entity.java:895) [vg.class:?]
>       at net.minecraft.entity.EntityLivingBase.func_191986_a(EntityLivingBase.java:1949) [vp.class:?]
>       at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2384) [vp.class:?]
>       at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577) [vq.class:?]
>       at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45) [ade.class:?]
>       at org.cyclops.evilcraft.entity.monster.Werewolf.func_70636_d(Werewolf.java:151) [Werewolf.class:?]
>       at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170) [vp.class:?]
>       at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) [vq.class:?]
```
