### ISSUE TITLE
Client crash while rendering chalice

### ISSUE THREAD

**Issue by flamechair** [rubensworks/EvilCraft#710]
#### Issue type:

- :bug: Bug

____

#### Short description:

Client crashes due to issue with rendering chalice

#### Steps to reproduce the problem:

1. Place chalice and wait

#### Expected behaviour:

____

#### Versions:

- This mod: EvilCraft-1.12.2-0.10.61
- Minecraft: 1.12.2
- Forge: 1.12.2 2705

#### Log file: https://gist.github.com/iamtpage/222a8bd3f5931b763f62f4feef8f54d9
```
java.lang.NullPointerException: Rendering Block Entity
	at org.cyclops.evilcraft.client.render.tileentity.RenderTileEntityEntangledChalice.render(RenderTileEntityEntangledChalice.java:25)
	at org.cyclops.evilcraft.client.render.tileentity.RenderTileEntityEntangledChalice.func_192841_a(RenderTileEntityEntangledChalice.java:19)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:155)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:130)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:705)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1345)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by rubensworks** [comment]
This one keeps coming back in a different form...
