### ISSUE TITLE
Vengeance spirit console spam

### ISSUE THREAD

**Issue by gakn** [rubensworks/EvilCraft#751]
#### Issue type:

- :question: Question

____

#### Question:

Is it possible to get some assistance/guidance to how I'd fix this log spam I'm getting every 10-18 seconds?

https://pastebin.com/Ze52gGwm

**Comment by rubensworks** [comment]
That looks like a bug. Could you send me the full Forge log?

**Comment by gakn** [comment]
[latest.log](https://github.com/CyclopsMC/EvilCraft/files/2824959/latest.log)
I hope this is the right log file, if it's not please provide some further direction in finding it, thank you.

It seems to happen only when I'm logged into the server, when no one is on it doesn't happen.

**Comment by rubensworks** [comment]
It may be caused by Pixelmon, but I'll look into it a bit more first.

```
[17:51:29] [Server thread/INFO] [STDERR]: [org.cyclops.evilcraft.core.helper.obfuscation.ObfuscationHelpers:getAmbientSound:79]: java.lang.reflect.InvocationTargetException
[17:51:29] [Server thread/INFO] [STDERR]: [org.cyclops.evilcraft.core.helper.obfuscation.ObfuscationHelpers:getAmbientSound:79]: 	at sun.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)
[17:51:29] [Server thread/INFO] [STDERR]: [org.cyclops.evilcraft.core.helper.obfuscation.ObfuscationHelpers:getAmbientSound:79]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:51:29] [Server thread/INFO] [STDERR]: [org.cyclops.evilcraft.core.helper.obfuscation.ObfuscationHelpers:getAmbientSound:79]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[17:51:29] [Server thread/INFO] [STDERR]: [org.cyclops.evilcraft.core.helper.obfuscation.ObfuscationHelpers:getAmbientSound:79]: 	at org.cyclops.evilcraft.core.helper.obfuscation.ObfuscationHelpers.getAmbientSound(ObfuscationHelpers.java:73)
[17:51:29] [Server thread/INFO] [STDERR]: [org.cyclops.evilcraft.core.helper.obfuscation.ObfuscationHelpers:getAmbientSound:79]: 	at org.cyclops.evilcraft.entity.monster.VengeanceSpirit.func_184639_G(VengeanceSpirit.java:637)
[17:51:29] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.NullPointerException
[17:51:29] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at com.pixelmonmod.pixelmon.entities.pixelmon.Entity9HasSounds.func_184639_G(Entity9HasSounds.java:25)
[17:51:29] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	... 23 more
```
