### ISSUE TITLE
Crash when interacting with the Blood Infuser

### ISSUE THREAD

**Issue by ghost** [rubensworks/EvilCraft#776]
#### Issue type:

- :bug: Bug

____

#### Short description:

Seemingly at random, the Blood Infuser will crash when right-clicking to open the GUI
```
java.lang.ArithmeticException: / by zero
	at org.cyclops.evilcraft.core.client.gui.container.GuiContainerTankInventory.func_146979_b(GuiContainerTankInventory.java:116)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:117)
	at org.cyclops.cyclopscore.client.gui.container.GuiContainerExtended.drawCurrentScreen(GuiContainerExtended.java:78)
	at org.cyclops.evilcraft.core.client.gui.container.GuiContainerTankInventory.drawCurrentScreen(GuiContainerTankInventory.java:129)
	at org.cyclops.cyclopscore.client.gui.container.GuiContainerExtended.func_73863_a(GuiContainerExtended.java:73)
...
```

#### Steps to reproduce the problem:

Unsure how to re-produce consistently because it seems to be random, but hopefully adding a simple safeguard to prevent ```/ by zero``` wouldn't be too much to ask.

#### Expected behaviour:

The game not to crash, obviously
____

#### Versions:

- This mod: 1.12.2-0.10.74
- Minecraft: 1.12.2
- Forge: 14.23.5.2838

#### Log file:

[Log](https://pastebin.com/jX3YRb8C)

**Comment by rubensworks** [comment]
Thanks for reporting, will look into it right away!
