### ISSUE TITLE
Persistent Crashing after killing pixies and having spectral glasses.

### ISSUE THREAD

**Issue by optmisticnihilist** [rubensworks/EvilCraft#858]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Persistent Crashing after killing Mana and Artifice pixies and having spectral glasses.

#### Steps to reproduce the problem:

1. /summon mana-and-artifice:pixie
2. kill pixie 
3. have spectral glasses inventory or add them to inventory shortly after.

#### Expected behaviour:

Spirit of pixie appearing.
____

#### Versions:

- This mod: EvilCraft-1.16.4-1.0.8.jar
- Minecraft: 1.16.4
- Forge: 35.1.7

I'm attempting to be a modpack author. I do also have an issue submitted to the Mana and Artifice author: https://github.com/Mithion/Mana-And-Artifice/issues/190 

Temporary solution was to blacklist the pixie from generating a spirit.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Relevant stacktrace:
```
java.lang.IllegalStateException: Pose stack not empty
	at net.minecraft.client.renderer.WorldRenderer.func_228423_a_(WorldRenderer.java:1193) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:lightoverlay-forge.mixins.json:MixinLevelRenderer,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.WorldRendererAccess,pl:mixin:APP:immersiveengineering.mixins.json:coremods.client.WorldRendererMixin,pl:mixin:APP:imm_ptl_mixins.json:client.render.MixinWorldRenderer,pl:mixin:APP:imm_ptl_mixins.json:client.render.MixinWorldRenderer_Clouds,pl:mixin:APP:imm_ptl_peripheral_mixins.json:client.alternate_dimension.MixinWorldRenderer_A,pl:mixin:APP:imm_ptl_peripheral_mixins.json:client.altius_world.MixinWorldRenderer_A,pl:mixin:APP:imm_ptl_mixins.json:client.render.MixinWorldRenderer_Optional,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1014) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:lightoverlay-forge.mixins.json:MixinLevelRenderer,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.WorldRendererAccess,pl:mixin:APP:immersiveengineering.mixins.json:coremods.client.WorldRendererMixin,pl:mixin:APP:imm_ptl_mixins.json:client.render.MixinWorldRenderer,pl:mixin:APP:imm_ptl_mixins.json:client.render.MixinWorldRenderer_Clouds,pl:mixin:APP:imm_ptl_peripheral_mixins.json:client.alternate_dimension.MixinWorldRenderer_A,pl:mixin:APP:imm_ptl_peripheral_mixins.json:client.altius_world.MixinWorldRenderer_A,pl:mixin:APP:imm_ptl_mixins.json:client.render.MixinWorldRenderer_Optional,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_client_renderer,pl:mixin:APP:totaldarkness.mixins.json:MixinGameRenderer,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinGameRenderer_B,pl:mixin:APP:imm_ptl_mixins.json:client.render.MixinGameRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.redirect$zjf000$redirectRenderingWorld(GameRenderer.java:1905) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_client_renderer,pl:mixin:APP:totaldarkness.mixins.json:MixinGameRenderer,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinGameRenderer_B,pl:mixin:APP:imm_ptl_mixins.json:client.render.MixinGameRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:425) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_client_renderer,pl:mixin:APP:totaldarkness.mixins.json:MixinGameRenderer,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinGameRenderer_B,pl:mixin:APP:imm_ptl_mixins.json:client.render.MixinGameRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:shutupexperimentalsettings.mixins.json:client.MixinMinecraft,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:shutupexperimentalsettings.mixins.json:client.MixinMinecraft,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
```

**Comment by optmisticnihilist** [comment]
Trying to figure out if the previous crashes without the glasses could be related. Does a spirit still generate but cannot be seen when not having a glasses, ring, or focus?

**Comment by rubensworks** [comment]
> Does a spirit still generate but cannot be seen when not having a glasses, ring, or focus?

Exactly. They are always generated, but only sometimes visible.

**Comment by rubensworks** [comment]
It doesn't look like this is something that can be fixed on my end.
The Mana and Artifice doesn't seem to be open-source, so I can't check why calling their renderer is breaking things.

I recommend following up with the mod author in https://github.com/Mithion/Mana-And-Artifice/issues/190.
This code may be relevant to mention: https://github.com/CyclopsMC/EvilCraft/blob/master-1.16/src/main/java/org/cyclops/evilcraft/client/render/entity/RenderVengeanceSpirit.java

If there's something that needs to be changed on my end, please let me know!

<blockquote><img src="https://avatars.githubusercontent.com/u/11808375?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/EvilCraft">CyclopsMC/EvilCraft</a></strong></div><div>An evil mod for Minecraft. Contribute to CyclopsMC/EvilCraft development by creating an account on GitHub.</div></blockquote>
