### ISSUE TITLE
[1.18.2 EC] Not launching

### ISSUE THREAD

**Issue by itsdinkd** [rubensworks/EvilCraft#918]
Issue with launching EvilCraft 1.1.24 with Latest Cyclops Core 1.18.2-1.15.0

```java
[09Jun2022 15:24:21.201] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: evilcraftcompat, class org.cyclops.evilcraftcompat.EvilCraftCompat
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.1.48.jar%23391!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.1.48.jar%23390!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.lang.NoSuchFieldError: INVENTORY_EXTENDERS
	at org.cyclops.evilcraftcompat.modcompat.curios.CuriosCompatLoader.initialize(CuriosCompatLoader.java:21) ~[EvilCraft-1.18.2-1.1.24.jar%23162!/:1.1.24]
	at org.cyclops.cyclopscore.modcompat.ModCompatLoader.addModCompat(ModCompatLoader.java:36) ~[CyclopsCore-1.18.2-1.15.0.jar%23136!/:1.15.0]
	at org.cyclops.evilcraftcompat.EvilCraftCompat.loadModCompats(EvilCraftCompat.java:46) ~[EvilCraft-1.18.2-1.1.24.jar%23162!/:1.1.24]
	at org.cyclops.cyclopscore.init.ModBase.<init>(ModBase.java:114) ~[CyclopsCore-1.18.2-1.15.0.jar%23136!/:1.15.0]
	at org.cyclops.cyclopscore.init.ModBaseVersionable.<init>(ModBaseVersionable.java:21) ~[CyclopsCore-1.18.2-1.15.0.jar%23136!/:1.15.0]
	at org.cyclops.evilcraftcompat.EvilCraftCompat.<init>(EvilCraftCompat.java:39) ~[EvilCraft-1.18.2-1.1.24.jar%23162!/:1.1.24]
	... 14 more
```

**Comment by rubensworks** [comment]
Please update to the latest EvilCraft version.
